baseurl = "https://fengkehh.github.io/"
title = "A Song of Numbers and Graphs"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "datakhf" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
relativeURLs = true


[Author]
    name = "Keh-Harng Feng"
    bio = "Keh-Harng Feng is aspiring to become a data scientist. He graduated from York University with a MSc in Physics and University of Toronto with a BSc in Computer Science and Physics."
    avatar = "img/avatar.png"


[Params]
    subtitle = "A Blog about Data Analysis" # Subtitle of your site
    description = "Keh-Harng Feng's Personal blog about Data and Statistics" # Description of your site
    opengraph = true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true


[Params.widgets]
    search = false # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = false # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[[menu.main]]
    name = "Blog Posts"
    weight = 1
    identifier = "posts"
    url = "/categories/posts/"
    
#[[menu.main]]
#    name = "Projects"
#    weight = 2
#    identifier = "projects"
#    url = "/categories/projects/"
